#ifndef __MM2S_RINGBUFFER_OFFSETS_H__
#define __MM2S_RINGBUFFER_OFFSETS_H__

#define MM2S_RINGBUFFERX____STRIDE          0x40

#define MM2S_RINGBUFFERX__CSR             0x00
#define MM2S_RINGBUFFERX__BASEADDRESS_LO  0x04
#define MM2S_RINGBUFFERX__BASEADDRESS_HI  0x08
#define MM2S_RINGBUFFERX__SIZE            0x0C
#define MM2S_RINGBUFFERX__HEADPTR         0x10
#define MM2S_RINGBUFFERX__TAILPTR         0x14
#define MM2S_RINGBUFFERX__WIDTH           0x18
#define MM2S_RINGBUFFERX__RESERVED        0x1C
#define MM2S_RINGBUFFERX__LEVEL_THRESHOLD 0x20
#define MM2S_RINGBUFFERX__INTR_ENABLE     0x24
#define MM2S_RINGBUFFERX__INTR_ACTIVE     0x28
#define MM2S_RINGBUFFERX__ID              0x2C
#define MM2S_RINGBUFFERX__VERSION         0x30
#define MM2S_RINGBUFFERX__SCRATCH         0x34

#endif
