module riscv_top_wrapper #(
    parameter CORE_ID                   = 0,
    parameter ICACHE_AXI_ID             = 0,
    parameter DCACHE_AXI_ID             = 0,
    parameter SUPPORT_BRANCH_PREDICTION = 1,
    parameter SUPPORT_MULDIV            = 1,
    parameter SUPPORT_SUPER             = 0,
    parameter SUPPORT_MMU               = 0,
    parameter SUPPORT_DUAL_ISSUE        = 1,
    parameter SUPPORT_LOAD_BYPASS       = 1,
    parameter SUPPORT_MUL_BYPASS        = 1,
    parameter SUPPORT_REGFILE_XILINX    = 0,
    parameter EXTRA_DECODE_STAGE        = 0,
    parameter MEM_CACHE_ADDR_MIN        = 32'h80000000,
    parameter MEM_CACHE_ADDR_MAX        = 32'h8fffffff,
    parameter NUM_BTB_ENTRIES           = 32,
    parameter NUM_BTB_ENTRIES_W         = 5,
    parameter NUM_BHT_ENTRIES           = 512,
    parameter NUM_BHT_ENTRIES_W         = 9,
    parameter RAS_ENABLE                = 1,
    parameter GSHARE_ENABLE             = 0,
    parameter BHT_ENABLE                = 1,
    parameter NUM_RAS_ENTRIES           = 8,
    parameter NUM_RAS_ENTRIES_W         = 3
) (
    input         i_clk,
    input         i_rst,
    input         i_intr,
    input  [31:0] i_reset_vector,
    output [31:0] s_data_axi_araddr,
    output [ 1:0] s_data_axi_arburst,
    output [ 3:0] s_data_axi_arid,
    output [ 7:0] s_data_axi_arlen,
    input         s_data_axi_arready,
    output        s_data_axi_arvalid,
    output [31:0] s_data_axi_awaddr,
    output [ 1:0] s_data_axi_awburst,
    output [ 3:0] s_data_axi_awid,
    output [ 7:0] s_data_axi_awlen,
    input         s_data_axi_awready,
    output        s_data_axi_awvalid,
    input  [ 3:0] s_data_axi_bid,
    output        s_data_axi_bready,
    input  [ 1:0] s_data_axi_bresp,
    input         s_data_axi_bvalid,
    input  [31:0] s_data_axi_rdata,
    input  [ 3:0] s_data_axi_rid,
    input         s_data_axi_rlast,
    output        s_data_axi_rready,
    input  [ 1:0] s_data_axi_rresp,
    input         s_data_axi_rvalid,
    output [31:0] s_data_axi_wdata,
    output        s_data_axi_wlast,
    input         s_data_axi_wready,
    output [ 3:0] s_data_axi_wstrb,
    output        s_data_axi_wvalid,
    output [31:0] s_instr_axi_araddr,
    output [ 1:0] s_instr_axi_arburst,
    output [ 3:0] s_instr_axi_arid,
    output [ 7:0] s_instr_axi_arlen,
    input         s_instr_axi_arready,
    output        s_instr_axi_arvalid,
    output [31:0] s_instr_axi_awaddr,
    output [ 1:0] s_instr_axi_awburst,
    output [ 3:0] s_instr_axi_awid,
    output [ 7:0] s_instr_axi_awlen,
    input         s_instr_axi_awready,
    output        s_instr_axi_awvalid,
    input  [ 3:0] s_instr_axi_bid,
    output        s_instr_axi_bready,
    input  [ 1:0] s_instr_axi_bresp,
    input         s_instr_axi_bvalid,
    input  [31:0] s_instr_axi_rdata,
    input  [ 3:0] s_instr_axi_rid,
    input         s_instr_axi_rlast,
    output        s_instr_axi_rready,
    input  [ 1:0] s_instr_axi_rresp,
    input         s_instr_axi_rvalid,
    output [31:0] s_instr_axi_wdata,
    output        s_instr_axi_wlast,
    input         s_instr_axi_wready,
    output [ 3:0] s_instr_axi_wstrb,
    output        s_instr_axi_wvalid
);

    riscv_top #(
        .CORE_ID                  (CORE_ID),
        .ICACHE_AXI_ID            (ICACHE_AXI_ID),
        .DCACHE_AXI_ID            (DCACHE_AXI_ID),
        .SUPPORT_BRANCH_PREDICTION(SUPPORT_BRANCH_PREDICTION),
        .SUPPORT_MULDIV           (SUPPORT_MULDIV),
        .SUPPORT_SUPER            (SUPPORT_SUPER),
        .SUPPORT_MMU              (SUPPORT_MMU),
        .SUPPORT_DUAL_ISSUE       (SUPPORT_DUAL_ISSUE),
        .SUPPORT_LOAD_BYPASS      (SUPPORT_LOAD_BYPASS),
        .SUPPORT_MUL_BYPASS       (SUPPORT_MUL_BYPASS),
        .SUPPORT_REGFILE_XILINX   (SUPPORT_REGFILE_XILINX),
        .EXTRA_DECODE_STAGE       (EXTRA_DECODE_STAGE),
        .MEM_CACHE_ADDR_MIN       (MEM_CACHE_ADDR_MIN),
        .MEM_CACHE_ADDR_MAX       (MEM_CACHE_ADDR_MAX),
        .NUM_BTB_ENTRIES          (NUM_BTB_ENTRIES),
        .NUM_BTB_ENTRIES_W        (NUM_BTB_ENTRIES_W),
        .NUM_BHT_ENTRIES          (NUM_BHT_ENTRIES),
        .NUM_BHT_ENTRIES_W        (NUM_BHT_ENTRIES_W),
        .RAS_ENABLE               (RAS_ENABLE),
        .GSHARE_ENABLE            (GSHARE_ENABLE),
        .BHT_ENABLE               (BHT_ENABLE),
        .NUM_RAS_ENTRIES          (NUM_RAS_ENTRIES),
        .NUM_RAS_ENTRIES_W        (NUM_RAS_ENTRIES_W)
    ) i_riscv_tcm_top (
        .clk_i          (i_clk),
        .rst_i          (i_rst),
        .intr_i         (i_intr),
        .reset_vector_i (i_reset_vector),
        .axi_i_araddr_o (s_instr_axi_araddr),
        .axi_i_arburst_o(s_instr_axi_arburst),
        .axi_i_arid_o   (s_instr_axi_arid),
        .axi_i_arlen_o  (s_instr_axi_arlen),
        .axi_i_arready_i(s_instr_axi_arready),
        .axi_i_arvalid_o(s_instr_axi_arvalid),
        .axi_i_awaddr_o (s_instr_axi_awaddr),
        .axi_i_awburst_o(s_instr_axi_awburst),
        .axi_i_awid_o   (s_instr_axi_awid),
        .axi_i_awlen_o  (s_instr_axi_awlen),
        .axi_i_awready_i(s_instr_axi_awready),
        .axi_i_awvalid_o(s_instr_axi_awvalid),
        .axi_i_bid_i    (s_instr_axi_bid),
        .axi_i_bready_o (s_instr_axi_bready),
        .axi_i_bresp_i  (s_instr_axi_bresp),
        .axi_i_bvalid_i (s_instr_axi_bvalid),
        .axi_i_rdata_i  (s_instr_axi_rdata),
        .axi_i_rid_i    (s_instr_axi_rid),
        .axi_i_rlast_i  (s_instr_axi_rlast),
        .axi_i_rready_o (s_instr_axi_rready),
        .axi_i_rresp_i  (s_instr_axi_rresp),
        .axi_i_rvalid_i (s_instr_axi_rvalid),
        .axi_i_wdata_o  (s_instr_axi_wdata),
        .axi_i_wlast_o  (s_instr_axi_wlast),
        .axi_i_wready_i (s_instr_axi_wready),
        .axi_i_wstrb_o  (s_instr_axi_wstrb),
        .axi_i_wvalid_o (s_instr_axi_wvalid),
        .axi_d_araddr_o (s_data_axi_araddr),
        .axi_d_arburst_o(s_data_axi_arburst),
        .axi_d_arid_o   (s_data_axi_arid),
        .axi_d_arlen_o  (s_data_axi_arlen),
        .axi_d_arready_i(s_data_axi_arready),
        .axi_d_arvalid_o(s_data_axi_arvalid),
        .axi_d_awaddr_o (s_data_axi_awaddr),
        .axi_d_awburst_o(s_data_axi_awburst),
        .axi_d_awid_o   (s_data_axi_awid),
        .axi_d_awlen_o  (s_data_axi_awlen),
        .axi_d_awready_i(s_data_axi_awready),
        .axi_d_awvalid_o(s_data_axi_awvalid),
        .axi_d_bid_i    (s_data_axi_bid),
        .axi_d_bready_o (s_data_axi_bready),
        .axi_d_bresp_i  (s_data_axi_bresp),
        .axi_d_bvalid_i (s_data_axi_bvalid),
        .axi_d_rdata_i  (s_data_axi_rdata),
        .axi_d_rid_i    (s_data_axi_rid),
        .axi_d_rlast_i  (s_data_axi_rlast),
        .axi_d_rready_o (s_data_axi_rready),
        .axi_d_rresp_i  (s_data_axi_rresp),
        .axi_d_rvalid_i (s_data_axi_rvalid),
        .axi_d_wdata_o  (s_data_axi_wdata),
        .axi_d_wlast_o  (s_data_axi_wlast),
        .axi_d_wready_i (s_data_axi_wready),
        .axi_d_wstrb_o  (s_data_axi_wstrb),
        .axi_d_wvalid_o (s_data_axi_wvalid)
    );
endmodule : riscv_top_wrapper
