module riscv_tcm_top_wrapper #(
    parameter BOOT_VECTOR               = 32'h00000000,
    parameter CORE_ID                   = 0,
    parameter TCM_MEM_BASE              = 32'h00000000,
    parameter SUPPORT_BRANCH_PREDICTION = 1,
    parameter SUPPORT_MULDIV            = 1,
    parameter SUPPORT_SUPER             = 0,
    parameter SUPPORT_MMU               = 0,
    parameter SUPPORT_DUAL_ISSUE        = 1,
    parameter SUPPORT_LOAD_BYPASS       = 1,
    parameter SUPPORT_MUL_BYPASS        = 1,
    parameter SUPPORT_REGFILE_XILINX    = 0,
    parameter EXTRA_DECODE_STAGE        = 0,
    parameter MEM_CACHE_ADDR_MIN        = 32'h80000000,
    parameter MEM_CACHE_ADDR_MAX        = 32'h8fffffff,
    parameter NUM_BTB_ENTRIES           = 32,
    parameter NUM_BTB_ENTRIES_W         = 5,
    parameter NUM_BHT_ENTRIES           = 512,
    parameter NUM_BHT_ENTRIES_W         = 9,
    parameter RAS_ENABLE                = 1,
    parameter GSHARE_ENABLE             = 0,
    parameter BHT_ENABLE                = 1,
    parameter NUM_RAS_ENTRIES           = 8,
    parameter NUM_RAS_ENTRIES_W         = 3
) (
    input        i_clk,
    input        i_rst,
    input        i_rst_cpu,
    input [31:0] i_intr,

    output        s_axi_awready,
    input         s_axi_awvalid,
    input  [31:0] s_axi_awaddr,
    input  [ 3:0] s_axi_awid,
    input  [ 7:0] s_axi_awlen,
    input  [ 1:0] s_axi_awburst,
    output        s_axi_wready,
    input         s_axi_wvalid,
    input  [31:0] s_axi_wdata,
    input  [ 3:0] s_axi_wstrb,
    input         s_axi_wlast,
    input         s_axi_bready,
    output        s_axi_bvalid,
    output [ 1:0] s_axi_bresp,
    output [ 3:0] s_axi_bid,
    output        s_axi_arready,
    input         s_axi_arvalid,
    input  [31:0] s_axi_araddr,
    input  [ 3:0] s_axi_arid,
    input  [ 7:0] s_axi_arlen,
    input  [ 1:0] s_axi_arburst,
    input         s_axi_rready,
    output        s_axi_rvalid,
    output [31:0] s_axi_rdata,
    output [ 1:0] s_axi_rresp,
    output [ 3:0] s_axi_rid,
    output        s_axi_rlast,
    input         m_axil_awready,
    output        m_axil_awvalid,
    output [31:0] m_axil_awaddr,
    input         m_axil_wready,
    output        m_axil_wvalid,
    output [31:0] m_axil_wdata,
    output [ 3:0] m_axil_wstrb,
    output        m_axil_bready,
    input         m_axil_bvalid,
    input  [ 1:0] m_axil_bresp,
    output        m_axil_arvalid,
    input         m_axil_arready,
    output [31:0] m_axil_araddr,
    input         m_axil_rvalid,
    input  [31:0] m_axil_rdata,
    input  [ 1:0] m_axil_rresp,
    output        m_axil_rready
);

    riscv_tcm_top #(
        .BOOT_VECTOR              (BOOT_VECTOR),
        .CORE_ID                  (CORE_ID),
        .TCM_MEM_BASE             (TCM_MEM_BASE),
        .SUPPORT_BRANCH_PREDICTION(SUPPORT_BRANCH_PREDICTION),
        .SUPPORT_MULDIV           (SUPPORT_MULDIV),
        .SUPPORT_SUPER            (SUPPORT_SUPER),
        .SUPPORT_MMU              (SUPPORT_MMU),
        .SUPPORT_DUAL_ISSUE       (SUPPORT_DUAL_ISSUE),
        .SUPPORT_LOAD_BYPASS      (SUPPORT_LOAD_BYPASS),
        .SUPPORT_MUL_BYPASS       (SUPPORT_MUL_BYPASS),
        .SUPPORT_REGFILE_XILINX   (SUPPORT_REGFILE_XILINX),
        .EXTRA_DECODE_STAGE       (EXTRA_DECODE_STAGE),
        .MEM_CACHE_ADDR_MIN       (MEM_CACHE_ADDR_MIN),
        .MEM_CACHE_ADDR_MAX       (MEM_CACHE_ADDR_MAX),
        .NUM_BTB_ENTRIES          (NUM_BTB_ENTRIES),
        .NUM_BTB_ENTRIES_W        (NUM_BTB_ENTRIES_W),
        .NUM_BHT_ENTRIES          (NUM_BHT_ENTRIES),
        .NUM_BHT_ENTRIES_W        (NUM_BHT_ENTRIES_W),
        .RAS_ENABLE               (RAS_ENABLE),
        .GSHARE_ENABLE            (GSHARE_ENABLE),
        .BHT_ENABLE               (BHT_ENABLE),
        .NUM_RAS_ENTRIES          (NUM_RAS_ENTRIES),
        .NUM_RAS_ENTRIES_W        (NUM_RAS_ENTRIES_W)
    ) i_riscv_tcm_top (
        .clk_i          (i_clk),
        .rst_i          (i_rst),
        .rst_cpu_i      (i_rst_cpu),
        .intr_i         (i_intr),
        //
        .axi_t_awvalid_i(s_axi_awvalid),
        .axi_t_awaddr_i (s_axi_awaddr),
        .axi_t_awid_i   (s_axi_awid),
        .axi_t_awlen_i  (s_axi_awlen),
        .axi_t_awburst_i(s_axi_awburst),
        .axi_t_wvalid_i (s_axi_wvalid),
        .axi_t_wdata_i  (s_axi_wdata),
        .axi_t_wstrb_i  (s_axi_wstrb),
        .axi_t_wlast_i  (s_axi_wlast),
        .axi_t_bready_i (s_axi_bready),
        .axi_t_arvalid_i(s_axi_arvalid),
        .axi_t_araddr_i (s_axi_araddr),
        .axi_t_arid_i   (s_axi_arid),
        .axi_t_arlen_i  (s_axi_arlen),
        .axi_t_arburst_i(s_axi_arburst),
        .axi_t_rready_i (s_axi_rready),
        .axi_t_awready_o(s_axi_awready),
        .axi_t_wready_o (s_axi_wready),
        .axi_t_bvalid_o (s_axi_bvalid),
        .axi_t_bresp_o  (s_axi_bresp),
        .axi_t_bid_o    (s_axi_bid),
        .axi_t_arready_o(s_axi_arready),
        .axi_t_rvalid_o (s_axi_rvalid),
        .axi_t_rdata_o  (s_axi_rdata),
        .axi_t_rresp_o  (s_axi_rresp),
        .axi_t_rid_o    (s_axi_rid),
        .axi_t_rlast_o  (s_axi_rlast),
        //
        .axi_i_awready_i(m_axil_awready),
        .axi_i_awvalid_o(m_axil_awvalid),
        .axi_i_awaddr_o (m_axil_awaddr),
        .axi_i_wready_i (m_axil_wready),
        .axi_i_wvalid_o (m_axil_wvalid),
        .axi_i_wdata_o  (m_axil_wdata),
        .axi_i_wstrb_o  (m_axil_wstrb),
        .axi_i_bready_o (m_axil_bready),
        .axi_i_bvalid_i (m_axil_bvalid),
        .axi_i_bresp_i  (m_axil_bresp),
        .axi_i_arvalid_o(m_axil_arvalid),
        .axi_i_arready_i(m_axil_arready),
        .axi_i_araddr_o (m_axil_araddr),
        .axi_i_rvalid_i (m_axil_rvalid),
        .axi_i_rdata_i  (m_axil_rdata),
        .axi_i_rresp_i  (m_axil_rresp),
        .axi_i_rready_o (m_axil_rready)
    );
endmodule : riscv_tcm_top_wrapper
